from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


class BaseSerializer(BaseModel):
    """
    Base serializer for all models.
    """
    class Config:
        orm_mode = True
        from_attributes = True


class SafeSerializer(BaseSerializer):
    """
    Serializer for safe (GET) requests.
    """
    id: Optional[int] = Field(None, description="Unique identifier (autogenerated)")
    created_at: Optional[datetime] = Field(None, description="Creation timestamp (autogenerated)")
    updated_at: Optional[datetime] = Field(None, description="Last update timestamp (autogenerated)")